name: Deploy nuget package

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.806
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: Pack
      run: dotnet pack --no-build --include-symbols --include-source --configuration Release stellar-dotnet-sdk /p:Version=${GITHUB_REF#refs/tags/}
    - name: Publish
      run: dotnet nuget push stellar-dotnet-sdk/bin/Release/stellar-dotnet-sdk.${GITHUB_REF#refs/tags/}.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}