name: Deploy nuget package

on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
      working-directory: src
    - name: Test
      run: dotnet test --no-build --configuration Release
      working-directory: src
    - name: Pack
      run: dotnet pack --no-build --include-symbols --include-source --configuration Release Swisschain.Sirius.Sdk /p:Version=${GITHUB_REF#refs/tags/}
      working-directory: src
    - name: Publish
      run: dotnet nuget push Swisschain.Sirius.Sdk/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
      working-directory: src